### ISSUE TITLE
setFilter() throws ApiResponseException

### ISSUE THREAD

**Issue by sunniswain** [brd6/notion-sdk-php#23]
I am performing a very simple database query. I am able to run it just fine without passing any filters, but when I try to pass set_cursor through to get the next batch of pages, it throws this error:

Fatal error:  Uncaught Brd6\NotionSdkPhp\Exception\ApiResponseException: body failed validation. Fix one:
body.filter.or should be defined, instead was `undefined`.
body.filter.and should be defined, instead was `undefined`.
body.filter.title should be defined, instead was `undefined`.
body.filter.rich_text should be defined, instead was `undefined`.
body.filter.number should be defined, instead was `undefined`.
body.filter.checkbox should be defined, instead was `undefined`.
body.filter.select should be defined, instead was `undefined`.
body.filter.multi_select should be defined, instead was `undefined`.
body.filter.status should be defined, instead was `undefined`.
body.filter.date should be defined, instead was `undefined`.
body.filter.people should be defined, instead was `undefined`.
body.filter.files should be defined, instead was `undefined`.
body.filter.url should be defined, instead was `undefined`.
body.filter.email should be defined, instead was `undefined`.
body.filter.phone_number should be defined, instead was `undefined`.
body.filter.relation should be defined, instead was `undefined`.
body.filter.created_by should be defined, instead was `undefined`.
body.filter.created_time should be defined, instead was `undefined`.
body.filter.last_edited_by should be defined, instead was `undefined`.
body.filter.last_edited_time should be defined, instead was `undefined`.
body.filter.formula should be defined, instead was `undefined`.
body.filter.rollup should be defined, instead was `undefined`.

This is the part of my code I'm running. It throws the exception in the second iteration when it passes through set_cursor.

$foodItemsArray = array();
$hasMore = true;
$nextCursor = "";
$i = 0;
while($hasMore) {
	echo $i++;
	$databaseRequest = new DatabaseRequest();
	if($nextCursor != "") $databaseRequest->setFilter(['start_cursor' => $nextCursor]);
	$foodItemsRequest = $notion->databases()->query($foodItemsDBID, $databaseRequest);
	$currArray = $foodItemsRequest->toArray();
	$hasMore = $currArray["has_more"];
	$nextCursor = $currArray["next_cursor"];
	$foodItemsArray = array_merge($foodItemsArray, $currArray["results"]);
}

I'm quite new to using the Notion API so I feel like there must be something very simple here I'm just missing!

**Comment by brd6** [comment]
To pass the `set_cursor` value in the query, you must use the `paginationRequest` argument.

Like this:
```PHP
$paginationRequest = new PaginationRequest();
if ($nextCursor !== null) {
    $paginationRequest->setStartCursor($nextCursor);
}
$foodItemsRequest = $notion->databases()->query($foodItemsDBID, $databaseRequest, $paginationRequest);
}
```

I hope it helps you 🙂

**Comment by sunniswain** [comment]
That's it! I knew it had to be simple. Thank you!
