### ISSUE TITLE
Status Property error

### ISSUE THREAD

**Issue by laHeud** [brd6/notion-sdk-php#24]
Hello, i'm quite new to Notion API. I tried to query a database in order to get one ticket depends on a property number. But after adding filter and query I get a message : The given property value "status" is unsupported.
I think that come from there is no StatusProperty class but i'm not sure. WDYT ?
Things is, if i dump the rawdata from tue query method, it works.

```
Here is my code from my controller : 
    $databaseRequest = new DatabaseRequest();
    $databaseRequest->setFilter([
        'property' => 'PlusID',
        'number' => [
            'equals' => 2,
        ],
    ]);
    $myPage = $notion->databases()->query('####', $databaseRequest);
    dump($myPage); die;
```

Thanks

**Comment by brd6** [comment]
You're right, the issue is due to the missing "StatusProperty" class. I'll submit a PR to add it when I have a moment. Meanwhile, you can submit a PR yourself, any help would be appreciated :)
Let me know if you need more help.
